// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL-Ga4izwMLnKwq7Ck_2E03DvmPhvgNHg',
    appId: '1:746846380829:web:35d6a0c6497351d012b7f4',
    messagingSenderId: '746846380829',
    projectId: 'flowo-4f708',
    authDomain: 'flowo-4f708.firebaseapp.com',
    storageBucket: 'flowo-4f708.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdOt4nK7zG7jcabkvvKTnGb7IYuLRBQ4',
    appId: '1:746846380829:android:1325e016be8e249012b7f4',
    messagingSenderId: '746846380829',
    projectId: 'flowo-4f708',
    storageBucket: 'flowo-4f708.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe63nCuGfEs0Z9wNBb8-0T_MVcnAkdwxk',
    appId: '1:746846380829:ios:ff755b62e132702d12b7f4',
    messagingSenderId: '746846380829',
    projectId: 'flowo-4f708',
    storageBucket: 'flowo-4f708.firebasestorage.app',
    iosBundleId: 'com.example.flowo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe63nCuGfEs0Z9wNBb8-0T_MVcnAkdwxk',
    appId: '1:746846380829:ios:ff755b62e132702d12b7f4',
    messagingSenderId: '746846380829',
    projectId: 'flowo-4f708',
    storageBucket: 'flowo-4f708.firebasestorage.app',
    iosBundleId: 'com.example.flowo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL-Ga4izwMLnKwq7Ck_2E03DvmPhvgNHg',
    appId: '1:746846380829:web:6906ffcbaadbec6412b7f4',
    messagingSenderId: '746846380829',
    projectId: 'flowo-4f708',
    authDomain: 'flowo-4f708.firebaseapp.com',
    storageBucket: 'flowo-4f708.firebasestorage.app',
  );
}
